### PR TITLE
Make cgi 7.8 ready

### PR DESCRIPTION
**Pull request by jhenahan**
Builds under the latest platform and 7.8-RC2.

A different approach than the one taken in the other PR.

There may be a more elegant solution, I just followed the
common pattern I've seen in a few other libraries.

The version bump may also be overly aggressive.

### CODE REVIEW

**Comment by relrod** [comment]
@andersk ping! Can this be merged? Current `cgi` on hackage does not build on 7.8.3.

**Comment by mpickering** [comment]
I tried this patch and the build still failed on MonadCatchIO-mtl.

**Comment by cheecheeo** [comment]
@mpickering using "The Glorious Glasgow Haskell Compilation System, version 7.8.3" and running `cabal -j install` with a fresh cabal sandbox works fine for me. Does it fail on a different version of the compiler?

**Comment by mpickering** [comment]
Ok this succeeds in a fresh sandbox but fails with mtl-2.2.1. Sorry for the incorrect report.

```
Configuring MonadCatchIO-mtl-0.3.0.5...
Building MonadCatchIO-mtl-0.3.0.5...
Preprocessing library MonadCatchIO-mtl-0.3.0.5...
[1 of 1] Compiling Control.Monad.CatchIO ( Control/Monad/CatchIO.hs, dist/dist-sandbox-b6663262/build/Control/Monad/CatchIO.o )

Control/Monad/CatchIO.hs:55:15: Not in scope: ‘E.block’

Control/Monad/CatchIO.hs:56:15: Not in scope: ‘E.unblock’
Failed to install MonadCatchIO-mtl-0.3.0.5
```

**Comment by cheecheeo** [comment]
@mpickering Is failing to build with `mtl-2.2.1` a blocker for `haskell-cgi`? See also: #1 I'm pretty sure the intent of this ticket is just to get `haskell-cgi` working with GHC 7.8

**Comment by cheecheeo** [comment]
cgi successfully builds with `mtl-2.2.1` with the following cabal command:
`cabal -j install --constraint=mtl==2.2.1 --constraint=MonadCatchIO-mtl==0.3.1.0 --allow-newer=MonadCatchIO-transformers` I'll reach out to the `MonadCatchIO-mtl` maintainer to up the bounds of the package.

**Comment by jhenahan** [comment]
@andersk ping!

**Comment by cheecheeo** [comment]
For those following this thread. I'm working with @cartazio to push a new version to hackage here: https://github.com/cheecheeo/haskell-cgi/pull/1 If you'd like to comment or follow along.
